/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
static yyconst short int yy_accept[326] =
    {   0,
        0,    0,   27,   25,   26,   25,   20,    2,   20,   20,
       20,   20,    8,   25,   21,   25,   19,   25,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,    1,    0,    9,   21,    1,   22,    8,   23,
        0,   11,   10,   10,    2,    2,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,    1,
       19,   19,   19,   19,   19,   19,    2,    0,    0,    0,
       11,   10,   10,   10,   19,   19,   19,   19,   19,   19,
       19,   19,    0,    0,    7,   19,   19,   19,   19,   19,
       19,   12,   19,   19,   19,   19,    0,   19,   19,    0,

        0,   19,   19,   19,   19,    6,   19,    5,   19,    0,
        0,    0,    0,   19,   19,    0,   19,    0,    0,    3,
       19,   19,   19,   19,   19,   19,    0,   14,    0,    0,
        0,   19,    0,    0,   19,    0,    0,    3,    3,    3,
        0,    3,    0,    4,    0,    0,   19,    0,    0,    0,
        0,   19,   19,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   13,    0,    0,    0,    3,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   19,   19,    0,   19,    0,    0,    0,    0,
        0,    0,    0,   13,    0,    3,    3,    3,    0,    0,

       24,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   15,    0,
       19,   19,    0,    0,    0,    0,    0,    0,    3,    3,
        3,    0,   24,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   17,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    3,    0,    0,    0,    0,    0,    0,   17,    0,
        0,   16,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   18,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    4,    1,    1,    5,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,    1,   16,
       17,   18,    1,    1,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
        1,    1,    1,   20,   21,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   19,   31,   32,   33,   34,
       35,   36,   19,   37,   38,   39,   40,   19,   41,   42,
       19,   19,   43,   44,   45,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[46] =
    {   0,
        1,    2,    3,    4,    1,    1,    5,    6,    1,    4,
        7,    4,    1,    1,    8,    1,    9,    1,   10,    1,
       11,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   12,    1,    1
    } ;

static yyconst short int yy_base[365] =
    {   0,
        0,    0,  807, 1047, 1047,  802,  788,   40,  784,   37,
       36,   41,   46,  783, 1047,  780,    0,  778,  760,   25,
       34,  761,   42,   22,  752,  754,  753,  760,  745,  746,
      753,  746,  747,  762,  761, 1047, 1047, 1047,   52, 1047,
       64,    0,   53,   71,  747,  746,    0,  737,  723,  730,
      733,  720,  715,  717,  710,  712,   67,  706,  711,    0,
      711,  701,  702,  698,  707,  699, 1047,   78,   82,   83,
        0,   73,  709,  705,  686,  695,  679,  676,  677,  649,
       86,  651,   68,    0,  669,  648,  636,  628,  637,  640,
      632,   91,  632,  632,   73,  635,  657,   87,   91,  649,

      652,  628,  614,  615,  617,    0,  623,    0,  614,   92,
      602,   93,   95,   99,  100,  642,  637,  101,  639,  107,
      604,  633,  605,  608,  108,  595,  589, 1047,  102,  111,
      598,  133,  624,  119,  623,  118,  129,  135,  625,  147,
      163,  166,  155,    0,  144,  619,  600,  173,  153,  179,
      174,  168,  176,  618,  181,  589,  592,  586,  579,  579,
      188,  572,  189,  608,  612,  192,  599,  202,  609,  597,
      231,  208,  603,  218,  197,  219,  235,  205,  211,  244,
      236,  233,  234,  253,  564,  263,  255,  590,  570,  582,
      564,  568,  563, 1047,  266,  262,  277,  309,  595,  330,

     1047,  186,  287,  303,  295,  313,  373,  375,  376,  379,
      381,  247,  257,  382,  279,  105,  264,  552, 1047,  384,
      387,  398,  412,  564,  558,  591,  570,  560,  397,  283,
      368,    0,  585,  104,  288,  450,  573,  379,  421,    0,
      494,  542,  495,  578,  396,  498,  501,  395,  401,  540,
      378,  496,  549,  554,  548,  541,  541,  575,  537,  551,
      540,  434,  395,  495,  291,    0,    0,  558, 1047,  509,
      527, 1047,  535,  547,  529,  533,  528,  568,  599,  529,
      534,  528,  519,  519,  520,  528,  501,  540,  509,  503,
      521,  514,  547,  526,  517,  511,  511,  185,  496,  484,

      510,  466,  480,  466,  416,  403,  635,  406,  377,  350,
      295,  299,    0,  254,  256,  247,  231,  191,  417,  121,
       94, 1047,   96,  503, 1047,  673,  678,  689,  701,  711,
      722,  732,  740,  749,  758,  768,  777,  786,  792,  801,
      810,  817,  828,  837,  847,  857,  866,  874,  886,  897,
      906,  915,  925,  937,  946,  958,  968,  978,  988,  998,
     1009, 1015, 1024, 1035
    } ;

static yyconst short int yy_def[365] =
    {   0,
      325,    1,  325,  325,  325,  326,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  327,  325,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  325,  326,  326,  325,  325,  325,  325,  325,
      328,  329,  325,  325,  325,  325,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  325,  328,  328,  328,
      329,  325,  325,  325,  327,  327,  327,  327,  327,  327,
      330,  327,  325,  331,  327,  327,  327,  327,  327,  327,
      327,  328,  327,  327,  327,  327,  332,  333,  334,  331,

      335,  327,  327,  327,  327,  327,  327,  327,  327,  325,
      336,  337,  325,  333,  333,  338,  339,  331,  335,  340,
      327,  327,  327,  327,  327,  327,  336,  325,  337,  337,
      325,  341,  342,  325,  339,  331,  343,  335,  335,  340,
      325,  340,  344,  327,  325,  345,  327,  346,  347,  347,
      325,  348,  348,  342,  325,  325,  325,  325,  325,  325,
      343,  349,  343,  331,  335,  325,  325,  335,  350,  325,
      344,  351,  345,  345,  352,  352,  347,  353,  353,  325,
      325,  325,  348,  348,  354,  355,  325,  325,  325,  325,
      325,  325,  325,  325,  343,  335,  335,  340,  350,  325,

      325,  171,  351,  203,  203,  203,  345,  356,  352,  352,
      357,  325,  353,  358,  325,  325,  325,  354,  325,  347,
      348,  348,  325,  325,  325,  359,  325,  325,  335,  335,
      198,  200,  350,  350,  200,  325,  171,  171,  203,  203,
      356,  360,  356,  345,  352,  352,  347,  353,  325,  361,
      325,  325,  325,  325,  325,  325,  325,  359,  362,  325,
      325,  335,  200,  236,  236,  236,  236,  171,  325,  356,
      361,  325,  325,  325,  325,  325,  325,  325,  362,  279,
      279,  279,  279,  279,  325,  325,  200,  200,  236,  236,
      325,  325,  325,  325,  325,  279,  279,  279,  279,  279,

      200,  325,  325,  325,  279,  279,  363,  279,  279,  364,
      325,  325,  279,  279,  279,  279,  279,  279,  279,  279,
      364,  325,  279,  279,    0,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325
    } ;

static yyconst short int yy_nxt[1093] =
    {   0,
        4,    5,    4,    6,    7,    8,    4,    4,    9,   10,
        4,   11,    4,   12,   13,   14,   15,   16,   17,   18,
        4,   19,   20,   21,   17,   22,   23,   17,   17,   24,
       17,   17,   17,   25,   26,   27,   28,   29,   30,   17,
       31,   32,    4,   33,    4,   37,   38,   40,   57,   41,
       39,   39,   36,   36,   42,   58,   36,   36,   43,   49,
       39,   50,   51,   54,   43,   69,   39,   72,   52,   83,
       83,   44,   70,   84,   84,  110,   55,   44,   44,   69,
       73,   56,   73,   69,   69,   74,   70,   72,   97,  113,
       70,   70,   69,  116,  110,  113,   92,  113,   44,   70,

       47,  113,  113,  136,  113,   47,   47,  200,  118,  138,
      145,   47,  215,  113,  146,  111,  115,  139,  235,  251,
      136,  140,  130,  141,  131,  118,  155,  140,  115,  115,
      162,  130,  307,  132,  111,  150,  163,  138,  322,  151,
      130,  156,  157,  137,  148,  139,  145,  114,  158,  138,
      146,  141,  159,  114,  324,  177,  160,  139,  169,  151,
      137,  140,  153,  141,  170,  166,  170,  140,  138,  171,
      182,  100,  167,  164,  167,  150,  139,  168,  182,  151,
      140,  150,  141,  187,  180,  151,  140,  129,  181,  162,
      162,  195,  188,  129,  166,  163,  163,  184,  325,  182,

      237,  167,  176,  167,  196,  184,  168,  212,  179,  186,
      185,  169,  139,  212,  197,  201,  168,  170,  185,  170,
      207,  182,  204,  307,  299,  174,  210,  198,  206,  300,
      100,  137,  164,  164,  169,  182,  182,  177,  201,  185,
      170,  151,  170,  202,  214,  171,  180,  185,  210,  212,
      181,  215,  211,  185,  216,  182,  203,  187,  217,  212,
      208,  185,  131,  184,  196,  220,  188,  162,  195,  151,
      299,  215,  139,  163,  216,  185,  185,  183,  217,  196,
      298,  249,  184,  183,  297,  196,  186,  139,  296,  185,
      169,  229,  222,  139,  201,  185,  238,  262,  238,  185,

      263,  239,  198,  263,  170,  185,  170,  206,  137,  204,
      164,  138,  170,  264,  170,  202,  290,  204,  230,  139,
      230,  250,  170,  231,  170,  141,  293,  204,  240,  140,
      199,  293,  199,  232,  199,  199,  199,  233,  199,  234,
      199,  234,  199,  199,  235,  199,  199,  199,  236,  199,
      199,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  199,  199,  199,  207,  242,  325,  182,  325,
      174,  182,  243,  220,  247,  215,  220,  151,  151,  182,
      151,  325,  251,  268,  322,  209,  213,  212,  182,  196,

      182,  209,  213,  249,  172,  210,  320,  139,  210,  287,
      246,  229,  211,  179,  252,  208,  184,  173,  185,  244,
      264,  185,  198,  185,  185,  210,  185,  184,  319,  185,
      170,  186,  170,  202,  253,  254,  196,  185,  185,  307,
      185,  255,  323,  250,  139,  256,  240,  307,  262,  257,
      199,  296,  199,  232,  199,  199,  199,  233,  199,  234,
      199,  234,  199,  199,  265,  199,  199,  199,  266,  199,
      267,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  199,  199,  199,  242,  242,  270,  252,  312,

      182,  243,  243,  247,  288,  311,  288,  151,  310,  289,
      242,  270,  288,  263,  288,  287,  243,  289,  253,  254,
      309,  263,  263,  289,  301,  255,  264,  210,  308,  256,
      307,  211,  306,  257,  290,  264,  173,  208,  244,  244,
      185,  307,  299,  185,  155,  305,  304,  278,  303,  302,
      293,  208,  293,  244,  301,  226,  226,  300,  299,  280,
      281,  298,  297,  296,  295,  294,  282,  293,  292,  291,
      283,  272,  268,  286,  284,  155,  285,  258,  278,  277,
      276,  275,  274,  273,  272,  174,  269,  237,  200,  261,
      156,  157,  260,  258,  226,  226,  219,  158,  200,  228,

      227,  159,  226,  225,  224,  160,  155,  223,  219,  278,
      174,  171,  200,  168,  165,  118,  194,  193,  192,  191,
      190,  280,  281,  189,  134,  108,  174,  165,  282,  134,
      134,  149,  283,  128,  147,   85,  284,  258,  144,  143,
       85,  119,  155,  134,  116,  278,  128,  126,  125,  279,
      124,  123,  122,  121,  119,  279,  118,  314,  315,   97,
      106,  109,  108,  107,  316,  106,  105,  104,  317,  103,
      102,  101,  318,   34,   99,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   47,   96,   47,   47,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,

       68,   71,   95,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   98,   94,   85,   93,   85,   98,   74,
       98,   98,  100,   74,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  112,   60,   91,   90,   89,   88,
       87,  112,  114,   86,   85,   82,   81,  114,   80,  114,
      114,  117,   79,   78,   77,   76,  117,   75,  117,  117,
      120,   60,   36,   36,   35,   35,   67,  120,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  129,
       66,   65,   64,   63,  129,   62,  129,  129,  133,   61,
       60,   59,   53,   48,   36,  133,  135,   46,   45,  135,

       36,  135,  135,  142,   36,   35,  325,  142,  142,  142,
      142,  142,  152,  325,  152,  325,  325,  152,  325,  152,
      152,  154,  325,  325,  154,  325,  154,  154,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      172,  325,  325,  325,  172,  325,  172,  173,  325,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  175,
      325,  175,  325,  325,  175,  325,  175,  175,  178,  325,
      178,  325,  325,  325,  325,  178,  183,  325,  325,  325,
      325,  183,  325,  183,  183,  183,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  199,  325,  199,

      199,  199,  199,  199,  199,  199,  199,  199,  199,  205,
      325,  205,  325,  205,  325,  205,  205,  209,  325,  325,
      325,  325,  209,  325,  209,  209,  209,  213,  325,  325,
      325,  325,  213,  325,  213,  213,  213,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  221,  325,
      221,  325,  325,  221,  325,  221,  221,  221,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      245,  325,  245,  325,  325,  245,  325,  245,  245,  245,
      248,  325,  248,  325,  325,  248,  325,  248,  248,  248,
      259,  325,  325,  325,  325,  325,  325,  259,  242,  242,

      242,  242,  242,  242,  242,  242,  242,  242,  242,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      279,  279,  279,  325,  279,  279,  313,  325,  325,  313,
      313,  313,  325,  313,  313,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,    3,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325

    } ;

static yyconst short int yy_chk[1093] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,   10,   11,   24,   12,
       11,   10,   11,   10,   12,   24,    8,   12,   13,   20,
       13,   20,   21,   23,   39,   41,   39,   43,   21,   57,
       83,   13,   41,   57,   83,   95,   23,   39,   43,   68,
       44,   23,   44,   69,   70,   44,   68,   72,   81,   98,
       69,   70,   92,   99,  110,  112,   70,  113,   72,   92,

       81,  114,  115,  118,  129,   99,   81,  234,  118,  120,
      125,   99,  216,  130,  125,   95,   98,  120,  234,  216,
      136,  120,  112,  120,  113,  136,  134,  120,  114,  115,
      137,  129,  323,  115,  110,  132,  137,  138,  321,  132,
      130,  134,  134,  118,  130,  138,  145,  132,  134,  140,
      145,  138,  134,  132,  320,  149,  134,  140,  143,  149,
      136,  140,  132,  140,  143,  141,  143,  140,  142,  143,
      152,  137,  141,  137,  141,  148,  142,  141,  153,  148,
      142,  150,  142,  155,  151,  150,  142,  148,  151,  161,
      163,  163,  155,  148,  166,  161,  163,  152,  202,  175,

      202,  166,  148,  166,  168,  153,  166,  178,  150,  153,
      152,  172,  168,  179,  168,  172,  168,  172,  153,  172,
      174,  176,  172,  298,  298,  174,  175,  168,  172,  318,
      161,  163,  161,  163,  171,  182,  183,  177,  171,  175,
      171,  177,  171,  171,  179,  171,  181,  178,  176,  212,
      181,  180,  176,  179,  180,  184,  171,  187,  180,  213,
      174,  176,  182,  183,  196,  186,  187,  195,  195,  186,
      317,  217,  196,  195,  217,  182,  183,  186,  217,  197,
      316,  215,  184,  186,  315,  230,  184,  197,  314,  212,
      203,  197,  186,  230,  203,  184,  203,  230,  203,  213,

      235,  203,  197,  265,  205,  186,  205,  203,  195,  205,
      195,  198,  204,  235,  204,  204,  265,  204,  198,  198,
      198,  215,  206,  198,  206,  198,  312,  206,  204,  198,
      200,  311,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  207,  208,  231,  209,  231,
      207,  210,  208,  211,  214,  251,  220,  211,  214,  221,
      220,  238,  251,  238,  310,  211,  214,  248,  245,  229,

      222,  211,  214,  249,  238,  209,  309,  229,  210,  263,
      211,  229,  210,  220,  223,  207,  221,  208,  209,  208,
      263,  210,  229,  211,  214,  245,  220,  222,  308,  221,
      239,  222,  239,  239,  223,  223,  262,  248,  245,  306,
      222,  223,  319,  249,  262,  223,  239,  305,  262,  223,
      236,  319,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  241,  243,  243,  252,  304,

      246,  241,  243,  247,  264,  303,  264,  247,  302,  264,
      270,  270,  290,  287,  290,  287,  270,  290,  252,  252,
      300,  289,  301,  289,  301,  252,  287,  246,  299,  252,
      324,  246,  297,  252,  289,  301,  241,  243,  241,  243,
      246,  324,  324,  247,  259,  296,  295,  259,  294,  293,
      292,  270,  291,  270,  288,  286,  285,  284,  283,  259,
      259,  282,  281,  280,  277,  276,  259,  275,  274,  273,
      259,  271,  268,  261,  259,  278,  260,  258,  278,  257,
      256,  255,  254,  253,  250,  244,  242,  237,  233,  228,
      278,  278,  227,  226,  225,  224,  218,  278,  199,  193,

      192,  278,  191,  190,  189,  278,  279,  188,  185,  279,
      173,  170,  169,  167,  165,  164,  162,  160,  159,  158,
      157,  279,  279,  156,  154,  147,  146,  139,  279,  135,
      133,  131,  279,  127,  126,  124,  279,  307,  123,  122,
      121,  119,  307,  117,  116,  307,  111,  109,  107,  307,
      105,  104,  103,  102,  101,  307,  100,  307,  307,   97,
       96,   94,   93,   91,  307,   90,   89,   88,  307,   87,
       86,   85,  307,  326,   82,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  327,   80,  327,  327,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  329,   79,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  330,   78,   77,   76,   75,  330,   74,
      330,  330,  331,   73,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  332,   66,   65,   64,   63,   62,
       61,  332,  333,   59,   58,   56,   55,  333,   54,  333,
      333,  334,   53,   52,   51,   50,  334,   49,  334,  334,
      335,   48,   46,   45,   35,   34,   33,  335,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  337,
       32,   31,   30,   29,  337,   28,  337,  337,  338,   27,
       26,   25,   22,   19,   18,  338,  339,   16,   14,  339,

        9,  339,  339,  340,    7,    6,    3,  340,  340,  340,
      340,  340,  341,    0,  341,    0,    0,  341,    0,  341,
      341,  342,    0,    0,  342,    0,  342,  342,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      344,    0,    0,    0,  344,    0,  344,  345,    0,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  346,
        0,  346,    0,    0,  346,    0,  346,  346,  347,    0,
      347,    0,    0,    0,    0,  347,  348,    0,    0,    0,
        0,  348,    0,  348,  348,  348,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  350,    0,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  351,
        0,  351,    0,  351,    0,  351,  351,  352,    0,    0,
        0,    0,  352,    0,  352,  352,  352,  353,    0,    0,
        0,    0,  353,    0,  353,  353,  353,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  355,    0,
      355,    0,    0,  355,    0,  355,  355,  355,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      357,    0,  357,    0,    0,  357,    0,  357,  357,  357,
      358,    0,  358,    0,    0,  358,    0,  358,  358,  358,
      359,    0,    0,    0,    0,    0,    0,  359,  360,  360,

      360,  360,  360,  360,  360,  360,  360,  360,  360,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      362,  362,  362,    0,  362,  362,  363,    0,    0,  363,
      363,  363,    0,  363,  363,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main.l"
#define INITIAL 0
#line 2 "main.l"
    //Definations

    #include<bits/stdc++.h>
    using namespace std;

    string s;
    int cntId=0,cntKey=0,cntStmt=0;

    void print(string comment,string message){
        cout<<"Input : "<<message<<"\n";
        cout<<"Token : "<<comment<<"\n\n";
    }
    map<string,bool>mp;

#line 735 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 49 "main.l"


#line 889 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 326 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1047 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 51 "main.l"
{s=yytext;print("logical operators",s);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 52 "main.l"
{s=yytext;print("bitwise operators",s);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "main.l"
{
    
    s=yytext;print("variable declare",s);

    vector<string>v;

    int pos = 0,len=s.size();
    for(int i=0 ; i<len ; i++){
        if(s[i] == ' '){
            pos = i+1;
            break;
        }
    }

    string t = "";

    for(int i=pos ; i<len ; i++){
        if(s[i] == ' ') continue;
        if(s[i] == '=' || s[i] == ','){
            if((t[0]>='a' && t[0]<='z') || (t[0]>='A' && t[0]<='Z')){
                v.push_back(t);
            }
            t = "";
        }
        else t += s[i];
    }
    if((t[0]>='a' && t[0]<='z') || (t[0]>='A' && t[0]<='Z')){
        v.push_back(t);
    }

    for(auto u:v){
        if(mp[u]) {
            cout<<"Error : "<<u<<" was initialized before.\n";
        }
        mp[u] = 1;
    }

}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 91 "main.l"
{s=yytext;print("return keyword",s);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 92 "main.l"
{s=yytext;print("skip keyword",s);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 93 "main.l"
{s=yytext;print("Boolean",s);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 94 "main.l"
{s=yytext;print("Datatype",s);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 95 "main.l"
{s=yytext;print("Integer",s);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 96 "main.l"
{s=yytext;print("String",s);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 97 "main.l"
{s=yytext;print("Number",s);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 98 "main.l"
{s=yytext;print("Single Line Comment",s);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 99 "main.l"
{s=yytext;print("Multi Line Comment",s);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 100 "main.l"
{s=yytext;print("if Condition",s);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 101 "main.l"
{s=yytext;print("else Condition",s);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 102 "main.l"
{s=yytext;print("for loop1",s);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 103 "main.l"
{s=yytext;print("for loop2",s);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 104 "main.l"
{s=yytext;print("while loop",s);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 105 "main.l"
{s=yytext;print("function",s);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 106 "main.l"
{s=yytext;print("Id",s);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 107 "main.l"
{s=yytext;print("math operators",s);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "main.l"
{s=yytext;print("assignment operators",s);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 109 "main.l"
{s=yytext;print("increment operator",s);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 110 "main.l"
{s=yytext;print("decrement operator",s);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 111 "main.l"
{s=yytext;print("print",s);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 112 "main.l"

	YY_BREAK
case 26:
YY_RULE_SETUP
#line 114 "main.l"
ECHO;
	YY_BREAK
#line 1139 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 326 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 326 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 325);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 114 "main.l"


int yywrap(){
    return 1;
}

int main(){
    
    yyin = freopen("temp.txt","r",stdin);
    cout<<"Evaluation is running... \n";
    yylex();

}